const PROJECTS = [
  {
    "project": "eMasinop",
    "description": null,
    "office": "SPMO",
    "priority": "Low",
    "status": "Not Started",
    "progress": null,
    "developers": "Arnold Celis, Bernard Secreto, Nestor Arcebuche",
    "start_date": null,
    "target_date": null,
    "deadline_fixed": "No",
    "effort": null,
    "dependencies": null,
    "notes": null
  },
  {
    "project": "KEC Conference",
    "description": null,
    "office": "FICS",
    "priority": "Medium",
    "status": "Development",
    "progress": null,
    "developers": "AJ Alarcon",
    "start_date": null,
    "target_date": null,
    "deadline_fixed": "Yes",
    "effort": "S",
    "dependencies": null,
    "notes": null
  },
  {
    "project": "ICDE Conference Website",
    "description": null,
    "office": "ICDE Committee",
    "priority": "Medium",
    "status": "Completed",
    "progress": null,
    "developers": "AJ Alarcon, Zak Pulmano",
    "start_date": null,
    "target_date": null,
    "deadline_fixed": "Yes",
    "effort": "S",
    "dependencies": null,
    "notes": null
  },
  {
    "project": "IFSS 2026 Website",
    "description": null,
    "office": "FMDS",
    "priority": "Medium",
    "status": "Completed",
    "progress": null,
    "developers": "AJ Alarcon",
    "start_date": null,
    "target_date": null,
    "deadline_fixed": "Yes",
    "effort": "S",
    "dependencies": null,
    "notes": null
  },
  {
    "project": "Commencement Exercise Website",
    "description": null,
    "office": "OUR",
    "priority": "Medium",
    "status": "Not Started",
    "progress": null,
    "developers": null,
    "start_date": null,
    "target_date": null,
    "deadline_fixed": null,
    "effort": "S",
    "dependencies": null,
    "notes": null
  },
  {
    "project": "OUP Volunteers Portal",
    "description": null,
    "office": "OUP",
    "priority": "Medium",
    "status": "Testing",
    "progress": null,
    "developers": "Arnold Celis",
    "start_date": null,
    "target_date": "2026-09-30",
    "deadline_fixed": "Yes",
    "effort": "M",
    "dependencies": null,
    "notes": null
  },
  {
    "project": "SAFE Disaster Monitoring System",
    "description": null,
    "office": "DRRM Committee",
    "priority": "High",
    "status": "Development",
    "progress": null,
    "developers": "Alex Bigal, Zak Pulmano",
    "start_date": null,
    "target_date": "2026-09-30",
    "deadline_fixed": "No",
    "effort": "M",
    "dependencies": null,
    "notes": null
  },
  {
    "project": "AIMS",
    "description": null,
    "office": "OUR",
    "priority": "High",
    "status": "Development",
    "progress": null,
    "developers": "Mark Sumaya, Alex Bigal",
    "start_date": "Recurring",
    "target_date": null,
    "deadline_fixed": "NA",
    "effort": "XL",
    "dependencies": null,
    "notes": null
  },
  {
    "project": "PIVOT",
    "description": null,
    "office": "UPOU",
    "priority": "High",
    "status": "Development",
    "progress": null,
    "developers": "Renz Magsino",
    "start_date": "Recurring",
    "target_date": null,
    "deadline_fixed": "NA",
    "effort": "XL",
    "dependencies": null,
    "notes": null
  },
  {
    "project": "FAIS",
    "description": null,
    "office": "Accounting Office",
    "priority": "High",
    "status": "Development",
    "progress": null,
    "developers": "Arnold Celis, James Telosa",
    "start_date": null,
    "target_date": "2026-12-31",
    "deadline_fixed": "Yes",
    "effort": "XL",
    "dependencies": null,
    "notes": null
  },
  {
    "project": "OAS with AI",
    "description": null,
    "office": "OUR",
    "priority": "Critical",
    "status": "Requirements",
    "progress": null,
    "developers": "Bernard Secreto, AJ Alarcon",
    "start_date": null,
    "target_date": "2027-01-31",
    "deadline_fixed": "Yes",
    "effort": "XL",
    "dependencies": null,
    "notes": null
  },
  {
    "project": "RPC Portal",
    "description": null,
    "office": "OVCAA",
    "priority": "Low",
    "status": "Not Started",
    "progress": null,
    "developers": null,
    "start_date": null,
    "target_date": null,
    "deadline_fixed": "No",
    "effort": "M",
    "dependencies": null,
    "notes": null
  },
  {
    "project": "Sustainability Website",
    "description": null,
    "office": "PDA for Sustainability",
    "priority": "Low",
    "status": "Not Started",
    "progress": null,
    "developers": null,
    "start_date": null,
    "target_date": null,
    "deadline_fixed": "No",
    "effort": "S",
    "dependencies": null,
    "notes": null
  },
  {
    "project": "MODeL Reconfiguration",
    "description": null,
    "office": "OUP",
    "priority": "Medium",
    "status": "Not Started",
    "progress": null,
    "developers": null,
    "start_date": null,
    "target_date": "2026-12-15",
    "deadline_fixed": "Yes",
    "effort": "S",
    "dependencies": null,
    "notes": null
  }
];
